<?php
/**
 * Automated Database Backup Script
 * Creates mysqldump backups with rotation (7 daily + 4 weekly)
 *
 * Usage:
 *   CLI:  php scripts/backup_database.php
 *   Cron: 0 2 * * * php /path/to/scripts/backup_database.php
 *   Web:  Can be triggered by admin via admin panel
 */

define('APP_ACCESS', true);

// Determine if running from CLI or web
$is_cli = (php_sapi_name() === 'cli');

if (!$is_cli) {
    // Web mode - require admin auth
    require_once __DIR__ . '/../includes/config.php';
    require_once __DIR__ . '/../includes/functions.php';
    require_once __DIR__ . '/../includes/auth.php';

    require_login();
    require_admin();

    // Rate limit
    if (!check_rate_limit('backup', 3, 3600)) {
        json_response(['success' => false, 'message' => 'Too many backup requests. Please wait 1 hour.'], 429);
    }

    header('Content-Type: application/json');
} else {
    // CLI mode - load config directly
    require_once __DIR__ . '/../includes/config.php';
    require_once __DIR__ . '/../includes/functions.php';
}

// Configuration
$backup_dir = __DIR__ . '/../backups';
$max_daily_backups = 7;
$max_weekly_backups = 4;
$date = date('Y-m-d_His');
$day_of_week = date('N'); // 1 = Monday, 7 = Sunday

// Ensure backup directory exists
if (!is_dir($backup_dir)) {
    mkdir($backup_dir, 0750, true);
}

// Write .htaccess to prevent web access to backups
$htaccess = $backup_dir . '/.htaccess';
if (!file_exists($htaccess)) {
    file_put_contents($htaccess, "Deny from all\n");
}

// Write .gitignore
$gitignore = $backup_dir . '/.gitignore';
if (!file_exists($gitignore)) {
    file_put_contents($gitignore, "*\n!.gitignore\n!.htaccess\n");
}

try {
    // Determine backup type
    $is_weekly = ($day_of_week == 7); // Sunday
    $prefix = $is_weekly ? 'weekly' : 'daily';
    $filename = "backup_{$prefix}_{$date}.sql";
    $filepath = $backup_dir . '/' . $filename;

    // Try mysqldump first (preferred method)
    $mysqldump_path = '';
    $possible_paths = [
        'C:/xampp/mysql/bin/mysqldump.exe',
        '/usr/bin/mysqldump',
        '/usr/local/bin/mysqldump',
        'mysqldump'
    ];

    foreach ($possible_paths as $path) {
        if (file_exists($path) || $path === 'mysqldump') {
            $mysqldump_path = $path;
            break;
        }
    }

    $backup_success = false;

    if (!empty($mysqldump_path)) {
        // Use mysqldump
        $password_arg = !empty(DB_PASS) ? '-p' . escapeshellarg(DB_PASS) : '';
        $cmd = sprintf(
            '%s --host=%s --user=%s %s --single-transaction --routines --triggers %s > %s 2>&1',
            escapeshellarg($mysqldump_path),
            escapeshellarg(DB_HOST),
            escapeshellarg(DB_USER),
            $password_arg,
            escapeshellarg(DB_NAME),
            escapeshellarg($filepath)
        );

        exec($cmd, $output, $return_code);

        if ($return_code === 0 && file_exists($filepath) && filesize($filepath) > 100) {
            $backup_success = true;
        }
    }

    // Fallback: PDO-based export if mysqldump fails
    if (!$backup_success) {
        $tables_stmt = $pdo->query("SHOW TABLES");
        $tables = $tables_stmt->fetchAll(PDO::FETCH_COLUMN);

        $sql_dump = "-- Database Backup: " . DB_NAME . "\n";
        $sql_dump .= "-- Date: " . date('Y-m-d H:i:s') . "\n";
        $sql_dump .= "-- Generated by Pre-Hospital Care System backup script\n\n";
        $sql_dump .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

        foreach ($tables as $table) {
            // Get CREATE TABLE statement
            $create_stmt = $pdo->query("SHOW CREATE TABLE `$table`");
            $create_row = $create_stmt->fetch();
            $sql_dump .= "DROP TABLE IF EXISTS `$table`;\n";
            $sql_dump .= $create_row['Create Table'] . ";\n\n";

            // Get data
            $data_stmt = $pdo->query("SELECT * FROM `$table`");
            $rows = $data_stmt->fetchAll(PDO::FETCH_ASSOC);

            if (!empty($rows)) {
                $columns = array_keys($rows[0]);
                $col_list = '`' . implode('`, `', $columns) . '`';

                foreach (array_chunk($rows, 100) as $chunk) {
                    $values = [];
                    foreach ($chunk as $row) {
                        $escaped = array_map(function($v) use ($pdo) {
                            return $v === null ? 'NULL' : $pdo->quote($v);
                        }, array_values($row));
                        $values[] = '(' . implode(', ', $escaped) . ')';
                    }
                    $sql_dump .= "INSERT INTO `$table` ($col_list) VALUES\n" . implode(",\n", $values) . ";\n\n";
                }
            }
        }

        $sql_dump .= "SET FOREIGN_KEY_CHECKS=1;\n";

        if (file_put_contents($filepath, $sql_dump) !== false) {
            $backup_success = true;
        }
    }

    if (!$backup_success) {
        throw new Exception('Backup failed: could not create backup file');
    }

    // Compress if gzip available
    $compressed = false;
    if (function_exists('gzopen')) {
        $gz_filepath = $filepath . '.gz';
        $gz = gzopen($gz_filepath, 'w9');
        if ($gz) {
            gzwrite($gz, file_get_contents($filepath));
            gzclose($gz);
            unlink($filepath); // Remove uncompressed
            $filepath = $gz_filepath;
            $filename .= '.gz';
            $compressed = true;
        }
    }

    // Cleanup old backups (rotation)
    $pattern_daily = $backup_dir . '/backup_daily_*';
    $pattern_weekly = $backup_dir . '/backup_weekly_*';

    $daily_files = glob($pattern_daily);
    $weekly_files = glob($pattern_weekly);

    // Sort by modification time (oldest first)
    usort($daily_files, function($a, $b) { return filemtime($a) - filemtime($b); });
    usort($weekly_files, function($a, $b) { return filemtime($a) - filemtime($b); });

    // Remove excess daily backups
    while (count($daily_files) > $max_daily_backups) {
        $old = array_shift($daily_files);
        unlink($old);
    }

    // Remove excess weekly backups
    while (count($weekly_files) > $max_weekly_backups) {
        $old = array_shift($weekly_files);
        unlink($old);
    }

    $file_size = filesize($filepath);
    $message = "Backup created: $filename (" . round($file_size / 1024, 1) . " KB)";

    if (!$is_cli) {
        log_activity('database_backup', $message);
        json_response([
            'success' => true,
            'message' => $message,
            'filename' => $filename,
            'size' => $file_size,
            'compressed' => $compressed
        ]);
    } else {
        echo "[OK] $message\n";
    }

} catch (Exception $e) {
    $error_msg = "Backup error: " . $e->getMessage();
    error_log($error_msg);

    if (!$is_cli) {
        json_response(['success' => false, 'message' => $error_msg], 500);
    } else {
        echo "[ERROR] $error_msg\n";
        exit(1);
    }
}
