<?php
/**
 * Secure File Serving Script
 * Serves uploaded files with authentication and security checks
 */

define('APP_ACCESS', true);
require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/functions.php';
require_once __DIR__ . '/../includes/auth.php';

// Require authentication
require_login();

// Rate limiting for file downloads
if (!check_rate_limit('file_download', 30, 60)) {
    http_response_code(429);
    die('Too many requests. Please try again later.');
}

// Get file path from query parameter
$filePath = $_GET['file'] ?? '';

if (empty($filePath)) {
    http_response_code(400);
    die('Invalid file path');
}

// Normalize the legacy ../uploads/... values generated by existing pages.
// The normalized value must still be an uploads-relative path.
$path_parts = [];
foreach (explode('/', str_replace('\\', '/', (string)$filePath)) as $part) {
    if ($part === '' || $part === '.') continue;
    if ($part === '..') {
        array_pop($path_parts);
        continue;
    }
    $path_parts[] = $part;
}
$stored_path = implode('/', $path_parts);
if (strpos($stored_path, 'uploads/') !== 0 || strpos($stored_path, '..') !== false) {
    http_response_code(403);
    die('Access denied');
}

// A file is only downloadable when it is attached to a record the current
// user is authorized to view. This prevents authenticated users from guessing
// another patient file's URL.
$record_stmt = db_query(
    "SELECT id FROM prehospital_forms
     WHERE patient_documentation = ? OR endorsement_attachment = ? OR waiver_attachment = ?
     LIMIT 1",
    [$stored_path, $stored_path, $stored_path]
);
$record = $record_stmt ? $record_stmt->fetch() : null;
if (!$record || !can_access_record((int)$record['id'])) {
    http_response_code(403);
    die('Access denied');
}

$realPath = resolve_upload_path($stored_path);
if ($realPath === false) {
    // Support legacy files that were saved under public/uploads until they are
    // migrated. Direct web access is blocked by public/uploads/.htaccess.
    $legacy_root = realpath(__DIR__ . '/../public/uploads');
    $legacy_candidate = realpath(__DIR__ . '/../public/' . $stored_path);
    if ($legacy_root && $legacy_candidate && strpos($legacy_candidate, $legacy_root . DIRECTORY_SEPARATOR) === 0) {
        $realPath = $legacy_candidate;
    }
}

if (!$realPath) {
    http_response_code(404);
    die('File not found');
}

// Check if file exists
if (!file_exists($realPath)) {
    http_response_code(404);
    die('File not found');
}

// Get file info
$fileSize = filesize($realPath);
$finfo = finfo_open(FILEINFO_MIME_TYPE);
$mimeType = finfo_file($finfo, $realPath);
finfo_close($finfo);
if (!in_array($mimeType, ['image/jpeg', 'image/png', 'image/gif', 'image/webp'], true)) {
    http_response_code(415);
    die('Unsupported file type');
}

// Set headers for secure serving
header('Content-Type: ' . $mimeType);
header('Content-Length: ' . $fileSize);
header('Content-Disposition: inline; filename="' . basename($realPath) . '"');
header('Cache-Control: private, max-age=3600');
header('X-Content-Type-Options: nosniff');
header('X-Frame-Options: DENY');

// Log file access
log_activity('file_access', 'Accessed file: ' . basename($realPath));

// Output file content
readfile($realPath);
exit();
